# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Koltin CI with bash

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for BUILD
      run: chmod +x ./src/application/build/BUILD.sh
    - name: Grant execute permission for TEST
      run: chmod +x ./src/application/build/TEST.sh
    - name: Build with BUILD.sh
      run: ./src/application/build/BUILD.sh
    - name: Run tests with TEST.sh
      run: ./src/application/build/TEST.sh
